Matteo
Dekleor/exo-computer-grp2 pull request #21
Opened 2021-03-01 15:56 UTC by Dekleor

2021-03-01 16:00 UTC, hardkos77 commented
Component

2021-03-02 08:38 UTC, Dreeckan requested changes

2021-03-02 08:38 UTC, Dreeckan commented on .gitignore
> +.idea
Tu peux te contenter de cette ligne pour ignorer ;)

2021-03-02 08:38 UTC, Dreeckan commented on .idea/.gitignore
> +# Default ignored files
Pour supprimer les fichiers de .idea, tu peux faire `git rm -r .idea`

2021-03-02 08:42 UTC, Alice1360 approved these changes
\o/

2021-03-02 08:42 UTC, Dreeckan approved these changes

2021-03-02 08:42 UTC, merged